### ISSUE TITLE
No oil

### ISSUE THREAD

**Issue by breadmoney** [ajgeiss0702/bigresources#2]
The oil doesnt work fam. I jus wanna get some oil :((

**Comment by ajgeiss0702** [comment]
The oil rig gives you gold

**Comment by ajgeiss0702** [comment]
The oil rig gives you gold






AstroServers Owner

AstroGmod Website <http://gmod.ajg0702.us>
My Steam page <http://steamcommunity.com/id/ajgeiss0702>
My addon <http://maprotate.ajg0702.us>
